-- Quoted fields/names avoid reserved keyword confusion.
SET SQL_MODE=ANSI_QUOTES

CREATE DATABASE IF NOT EXISTS property;
USE property;

DROP TABLE IF EXISTS PROPERTY_VALUE;
DROP TABLE IF EXISTS "DATE";
DROP TABLE IF EXISTS PROPERTY_LOCATION;
DROP TABLE IF EXISTS PROPERTY_SIZE;
DROP TABLE IF EXISTS PROPERTY_USE;

CREATE TABLE "DATE" (
	DateKey		MEDIUMINT	NOT NULL,
	FullDate	DATE		NOT NULL,
	"Year"		MEDIUMINT	NOT NULL,
	"Quarter"	MEDIUMINT	NOT NULL,
	"Month"		MEDIUMINT	NOT NULL,
	"Day"		MEDIUMINT	NOT NULL,
	PRIMARY KEY (DateKey)
);

CREATE TABLE PROPERTY_LOCATION (
	LocationKey	MEDIUMINT		NOT NULL,
	State		VARCHAR(2)		NOT NULL,
	City		VARCHAR(64)		NOT NULL,
	Street		VARCHAR(255) 	NOT NULL,
	ZIP5		MEDIUMINT		NOT NULL,
	PRIMARY KEY (LocationKey)
);

CREATE TABLE PROPERTY_USE (
	UseKey			MEDIUMINT		NOT NULL,
	GenericUse		VARCHAR(65)		NOT NULL,
	PropertyClass 	VARCHAR(255) 	NOT NULL,
	PRIMARY KEY (UseKey)
);

CREATE TABLE PROPERTY_SIZE (
	SizeKey			MEDIUMINT		NOT NULL,
	Acreage			DECIMAL(10, 2) 	NOT NULL,
	SquareFootage	BIGINT			NOT NULL,
	PRIMARY KEY (SizeKey)
);

CREATE TABLE PROPERTY_VALUE (
	ParcelID		VARCHAR(20)	NOT NULL,
	TransferDateKey		MEDIUMINT,
	AssessmentDateKey	MEDIUMINT,
	ImprovementDateKey	MEDIUMINT,
	UseKey			MEDIUMINT	NOT NULL,
	SizeKey			MEDIUMINT	NOT NULL,
	LocationKey		MEDIUMINT	NOT NULL,
	TotalValue			DECIMAL(20,2),
	LandValue			DECIMAL(20,2),
	ImprovementValue	DECIMAL(20,2),
	RecentSaleValue		DECIMAL(20,2),
	PRIMARY KEY (ParcelID),
	FOREIGN KEY (TransferDateKey) REFERENCES "DATE"(DateKey),
	FOREIGN KEY (AssessmentDateKey) REFERENCES "DATE"(DateKey),
	FOREIGN KEY (ImprovementDateKey) REFERENCES "DATE"(DateKey),
	FOREIGN KEY (UseKey) REFERENCES PROPERTY_USE(UseKey),
	FOREIGN KEY (SizeKey) REFERENCES PROPERTY_SIZE(SizeKey),
	FOREIGN KEY (LocationKey) REFERENCES PROPERTY_LOCATION(LocationKey)
);